source colors.sh

{echo -e "${Black} This is Black color${Drop}"
echo ""
echo -e "${White} This is White color${Drop}"
echo ""
echo -e "${Red} This is Red color${Drop}"
echo ""
echo -e "${Green} This is Green color${Drop}"
echo ""
echo -e "${Yellow} This is Yellow color${Drop}"
echo ""
echo -e "${Blue} This is Blue color${Drop}"
echo ""
echo -e "${Magenta} This is Magenta color${Drop}"
echo ""
echo -e "${Cyan} This is Cyan color${Drop}"
echo ""



echo -e "${Black}${GrayB} This is Black color on GrayB${Drop}"
echo ""
echo -e "${White}${GrayB} This is White color on GrayB${Drop}"
echo ""
echo -e "${Red}${GrayB} This is Red color on GrayB${Drop}"
echo ""
echo -e "${Green}${GrayB} This is Green color on GrayB${Drop}"
echo ""
echo -e "${Yellow}${GrayB} This is Yellow color on GrayB${Drop}"
echo ""
echo -e "${Blue}${GrayB} This is Blue color on GrayB${Drop}"
echo ""
echo -e "${Magenta}${GrayB} This is Magenta color on GrayB${Drop}"
echo ""
echo -e "${Cyan}${GrayB} This is Cyan color on GrayB${Drop}"
echo ""


echo -e "${Black}${BlackB} This is Black color on BlackB${Drop}"
echo ""
echo -e "${White}${BlackB} This is White color on BlackB${Drop}"
echo ""
echo -e "${Red}${BlackB} This is Red color on BlackB${Drop}"
echo ""
echo -e "${Green}${BlackB} This is Green color on BlackB${Drop}"
echo ""
echo -e "${Yellow}${BlackB} This is Yellow color on BlackB${Drop}"
echo ""
echo -e "${Blue}${BlackB} This is Blue color on BlackB${Drop}"
echo ""
echo -e "${Magenta}${BlackB} This is Magenta color on BlackB${Drop}"
echo ""
echo -e "${Cyan}${BlackB} This is Cyan color on BlackB${Drop}"
echo ""

echo -e "${Black}${WhiteB} This is Black color on WhiteB${Drop}"
echo ""
echo -e "${White}${WhiteB} This is White color on WhiteB${Drop}"
echo ""
echo -e "${Red}${WhiteB} This is Red color on WhiteB${Drop}"
echo ""
echo -e "${Green}${WhiteB} This is Green color on WhiteB${Drop}"
echo ""
echo -e "${Yellow}${WhiteB} This is Yellow color on WhiteB${Drop}"
echo ""
echo -e "${Blue}${WhiteB} This is Blue color on WhiteB${Drop}"
echo ""
echo -e "${Magenta}${WhiteB} This is Magenta color on WhiteB${Drop}"
echo ""
echo -e "${Cyan}${WhiteB} This is Cyan color on WhiteB${Drop}"
echo ""

echo -e "${Black}${RedB} This is Black color on RedB${Drop}"
echo ""
echo -e "${White}${RedB} This is White color on RedB${Drop}"
echo ""
echo -e "${Red}${RedB} This is Red color on RedB${Drop}"
echo ""
echo -e "${Green}${RedB} This is Green color on RedB${Drop}"
echo ""
echo -e "${Yellow}${RedB} This is Yellow color on RedB${Drop}"
echo ""
echo -e "${Blue}${RedB} This is Blue color on RedB${Drop}"
echo ""
echo -e "${Magenta}${RedB} This is Magenta color on RedB${Drop}"
echo ""
echo -e "${Cyan}${RedB} This is Cyan color on RedB${Drop}"
echo ""

echo -e "${Black}${GreenB} This is Black color on GreenB${Drop}"
echo ""
echo -e "${White}${GreenB} This is White color on GreenB${Drop}"
echo ""
echo -e "${Red}${GreenB} This is Red color on GreenB${Drop}"
echo ""
echo -e "${Green}${GreenB} This is Green color on GreenB${Drop}"
echo ""
echo -e "${Yellow}${GreenB} This is Yellow color on GreenB${Drop}"
echo ""
echo -e "${Blue}${GreenB} This is Blue color on GreenB${Drop}"
echo ""
echo -e "${Magenta}${GreenB} This is Magenta color on GreenB${Drop}"
echo ""
echo -e "${Cyan}${GreenB} This is Cyan color on GreenB${Drop}"
echo ""

echo -e "${Black}${YellowB} This is Black color on YellowB${Drop}"
echo ""
echo -e "${White}${YellowB} This is White color on YellowB${Drop}"
echo ""
echo -e "${Red}${YellowB} This is Red color on YellowB${Drop}"
echo ""
echo -e "${Green}${YellowB} This is Green color on YellowB${Drop}"
echo ""
echo -e "${Yellow}${YellowB} This is Yellow color on YellowB${Drop}"
echo ""
echo -e "${Blue}${YellowB} This is Blue color on YellowB${Drop}"
echo ""
echo -e "${Magenta}${YellowB} This is Magenta color on YellowB${Drop}"
echo ""
echo -e "${Cyan}${YellowB} This is Cyan color on YellowB${Drop}"
echo ""

echo -e "${Black}${BlueB} This is Black color on BlueB${Drop}"
echo ""
echo -e "${White}${BlueB} This is White color on BlueB${Drop}"
echo ""
echo -e "${Red}${BlueB} This is Red color on BlueB${Drop}"
echo ""
echo -e "${Green}${BlueB} This is Green color on BlueB${Drop}"
echo ""
echo -e "${Yellow}${BlueB} This is Yellow color on BlueB${Drop}"
echo ""
echo -e "${Blue}${BlueB} This is Blue color on BlueB${Drop}"
echo ""
echo -e "${Magenta}${BlueB} This is Magenta color on BlueB${Drop}"
echo ""
echo -e "${Cyan}${BlueB} This is Cyan color on BlueB${Drop}"
echo ""

echo -e "${Black}${MagentaB} This is Black color on MagentaB${Drop}"
echo ""
echo -e "${White}${MagentaB} This is White color on MagentaB${Drop}"
echo ""
echo -e "${Red}${MagentaB} This is Red color on MagentaB${Drop}"
echo ""
echo -e "${Green}${MagentaB} This is Green color on MagentaB${Drop}"
echo ""
echo -e "${Yellow}${MagentaB} This is Yellow color on MagentaB${Drop}"
echo ""
echo -e "${Blue}${MagentaB} This is Blue color on MagentaB${Drop}"
echo ""
echo -e "${Magenta}${MagentaB} This is Magenta color on MagentaB${Drop}"
echo ""
echo -e "${Cyan}${MagentaB} This is Cyan color on MagentaB${Drop}"
echo ""

echo -e "${Black}${CyanB} This is Black color on CyanB${Drop}"
echo ""
echo -e "${White}${CyanB} This is White color on CyanB${Drop}"
echo ""
echo -e "${Red}${CyanB} This is Red color on CyanB${Drop}"
echo ""
echo -e "${Green}${CyanB} This is Green color on CyanB${Drop}"
echo ""
echo -e "${Yellow}${CyanB} This is Yellow color on CyanB${Drop}"
echo ""
echo -e "${Blue}${CyanB} This is Blue color on CyanB${Drop}"
echo ""
echo -e "${Magenta}${CyanB} This is Magenta color on CyanB${Drop}"
echo ""
echo -e "${Cyan}${CyanB} This is Cyan color on CyanB${Drop}"
echo ""}